### ISSUE TITLE
Late chunking gets bad result when use Vietnamese Embedding Model

### ISSUE THREAD

**Issue by ki3nd** [jina-ai/late-chunking#17]
Thank you for the great work! I have tried using late chunking with the Vietnamese Embedding Model [dangvantuan/vietnamese-embedding-LongContext](https://huggingface.co/dangvantuan/vietnamese-embedding-LongContext), but I've observed poor results compared to traditional chunking methods.

I've included my Colab notebook [here](https://colab.research.google.com/drive/1JYas5VJWModbJfGZak0XDN8KTDQyR3g6?usp=sharing). If you have some time, could you please take a look? Your feedback would be greatly appreciated!

Thank you!

**Comment by guenthermi** [comment]
This model is using CLS pooling as far as I can see. Unfortunately, late chunking only works with models that are trained with mean pooling.
