### ISSUE TITLE
RuntimeError: [enforce fail at alloc_cpu.cpp:114] data. DefaultCPUAllocator: not enough memory: you tried to allocate 33507323568 bytes.

### ISSUE THREAD

**Issue by Godly-GM** [jina-ai/late-chunking#21]
I tried to pass the context from a 19-page PDF to the model, but I encountered this error:
RuntimeError: [enforce fail at alloc_cpu.cpp:114] data. DefaultCPUAllocator: not enough memory: you tried to allocate 33507323568 bytes.

here input_text is the content of pdf.
![Screenshot 2024-11-02 200912](https://github.com/user-attachments/assets/2180faad-bde0-44e8-aae8-02e71665d566)

**Comment by guenthermi** [comment]
It looks like your machine doesn't have enough memory to encode very long sequences of text. You could use the long late chunking method, which is implemented in the `_embed_with_overlap`  method (https://github.com/jina-ai/late-chunking/blob/db558c313a63a6b6f575281be9a3a87ad0fc1d4b/chunked_pooling/mteb_chunked_eval.py#L237) in our evaluation code together with a lower number of tokens (` long_late_chunking_embed_size`  in the function)  property to circumvent this issue.
