### ISSUE TITLE
Evaluation Code on LongEmbed Benchmark 

### ISSUE THREAD

**Issue by hanjiale** [jina-ai/late-chunking#22]
Thank you for the excellent work. Could you consider releasing the evaluation code for the LongEmbed Benchmark, as detailed in Figures 3 and 4 of the paper? This would greatly help in reproducing and building upon your research. Thanks!

**Comment by guenthermi** [comment]
Most of the code is already uploaded but the README is not up-to-date. I did not commit the implementation of the Passkey dataset yet. I will do this soon and also update the README but the other LongEmbed tasks are there. There was a small bug introduced by a recent change which was causing an exception when running the second type of evaluations, however, I just fixed it (https://github.com/jina-ai/late-chunking/commit/3b16f1e1f9f78d1bbdb40d7ef25eac15eb846724). There is not a single script to get all results, but to get each bar you can execute the following commands with different parameters:

Experiments in Figure 3:
```bash
python3 run_chunked_eval.py --model-name jinaai/jina-embeddings-v2-small-en --task-name LEMBQMSumRetrievalChunked --strategy fixed --truncate-max-length 8192 --chunk-size 128
```

Experiments in Figure 4:
```bash
python3 -m run_chunked_eval --model-name jinaai/jina-embeddings-v2-small-en --task-name LEMBQMSumRetrievalChunked --strategy fixed --long-late-chunking-embed-size 8192 --long-late-chunking-overlap-size 256 --chunk-size 128
```

If you have more questions, let me know.

**Comment by guenthermi** [comment]
The overlap used for the experiments in Figure 4 is 256, I am not sure if the paper is mentioning this.

**Comment by guenthermi** [comment]
Ok I also added the missing passkey dataset. If you evaluate Needle or Passkey, you need to add `--eval-split test_8192` as there are multiple test splits with text values of different length. The experiments which we had done for the paper using the 8192 split

**Comment by hanjiale** [comment]
Thank you for your prompt reply!
